# Generated by Django 2.2 on 2020-11-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Published', max_length=10),
        ),
    ]
