# Generated by Django 2.2 on 2020-12-02 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201130_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tag', models.CharField(default='Greeting of the day!', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Published', max_length=10)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='blog_archiveposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
