# Generated by Django 2.2 on 2020-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_archivepost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ArchivePost',
        ),
    ]
