# Generated by Django 3.1.4 on 2020-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_post_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Publish', max_length=10),
        ),
    ]
