# Generated by Django 3.1.4 on 2020-12-22 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201204_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
